# web server
server:
  port: 19092
  servlet:
    context-path: /h2

# spring
spring:
  application:
    name: h2-and-console
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
    platform: h2
    # 如果不希望h2启动时执行脚本,不仅不要指定schema和data的文件名,同时classpath下也不能存在空的文件
#    schema: classpath:schema.sql #可以自定义文件名
#    data: classpath:data.sql #可以自定义文件名
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true


# logging
logging:
  level:
    root: debug
    org:
      springframework: debug

